# Candidate Fundraising Analysis

In [24]:
# PREPARING DATA FOR MODEL AND VISUALIZATION
# STEP 1 - Importing Sheets
import pandas as pd
pd.set_option('display.max_columns', None)

kuntavaalit_ehdokas_sarakkeet = list(pd.read_csv("files/Results_title_rows_EN_ehdokas.csv")) # Saved as a list to apply to any candidate voting information, because header wasn't included in the data from the Ministry of Justice.

years_data = {
    2011: {
        'fundraising': "files/finances/Liite_1_Eduskuntavaalit_2011_RAHOITUSRIVIT_VI.csv"
    },
    2015: {
        'fundraising': "files/finances/Liite_3_Eduskuntavaalit_2015_RAHOITUSRIVIT_VI.csv"    
    },
    2019: {
        'fundraising': "files/finances/Liite_5_Eduskuntavaalit_2019_RAHOITUSRIVIT_VI.csv"
    },
    2023: {
        'fundraising': "files/finances/Liite_7_Eduskuntavaalit_2023_RAHOITUSRIVIT_VI.csv"
    }
}

all_years_data = []
for year, paths in years_data.items():
    print(f"Processing {year}...")
    year_df = pd.read_csv(paths['fundraising'], sep=";", quotechar="'", on_bad_lines='warn')
    year_df["Vuosi"] = year
    year_df["Tuen maara"] = year_df["Tuen maara"].replace({',':'.', " ":""}, regex=True).astype(float)
    all_years_data.append(year_df)

kuntavaalit_yhteensä_all = pd.concat(all_years_data, ignore_index=True)
print(f"In total, there were {len(all_years_data[0])} candidates recorded from 2012; {len(all_years_data[1])} from 2017; {len(all_years_data[2])} from 2021; and {len(all_years_data[3])} from 2025.")
display(kuntavaalit_yhteensä_all)

Processing 2011...
Processing 2015...
Processing 2019...
Processing 2023...
In total, there were 598 candidates recorded from 2012; 568 from 2017; 580 from 2021; and 888 from 2025.

,Tukija,Tukijan y-tunnus/yhdistysrekisterinumero jos on,Tukijan etunimet,Tukijan sukunimi,Tukijan kotikunta jos on,Tukilahteen lomakenumerot,Lainan nimi,Lainan takaisinmaksuaika/laina-aika,Tuen maara,Tuen saajan etunimet,Tuen saajan Sukunimi,Vaalipiiri / Kunta,Tuen saajan puolue,Vuosi
0,Kokoomuksen Valkeakosken Kunnallisjärjestö r.y.,138.274,NaN,NaN,NaN,2.6,NaN,NaN,11616.39,Pauli Antero,Kiuru,Pirkanmaan vaalipiiri,KOK,2011
1,"Rautatieläisten Liitto ry, Järnvägsarbetarnas ...",103.517,NaN,NaN,NaN,2.7,NaN,NaN,1900.00,Saara Elina,Karhu,Pirkanmaan vaalipiiri,SDP,2011
2,Tampereen Työväenyhdistys r.y.,0155655-3,NaN,NaN,NaN,2.6,NaN,NaN,3000.00,Pia-Liisa,Viitanen,Pirkanmaan vaalipiiri,SDP,2011
3,Pirkanpi ry,178.413,NaN,NaN,NaN,2.7,NaN,NaN,4304.00,Pia-Liisa,Viitanen,Pirkanmaan vaalipiiri,SDP,2011
4,Kokoomuksen Sastamalan Kunnallisjärjestö ry,127.590,NaN,NaN,NaN,2.6,NaN,NaN,2000.00,Arto Olavi,Satonen,Pirkanmaan vaalipiiri,KOK,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2629,"Kansallinen Kokoomus r.p., ruotsiksi Samlingsp...",0213498-5,NaN,NaN,NaN,2.5,NaN,NaN,2570.00,Heikki,Autto,Lapin vaalipiiri,KOK,2023
2630,Pro Markkinatalous ry,3134017-1,NaN,NaN,NaN,2.7,NaN,NaN,6000.00,Heikki,Autto,Lapin vaalipiiri,KOK,2023
2631,"Matkailu- ja Ravintolapalvelut MaRa ry, Turism...",0201951-4,NaN,NaN,NaN,2.7,NaN,NaN,5000.00,Heikki,Autto,Lapin vaalipiiri,KOK,2023
2632,Pro Markkinatalous ry,3134017-1,NaN,NaN,NaN,2.7,NaN,NaN,3000.00,Antti,Kaarlela,Lapin vaalipiiri,KOK,2023
2633,"Kansallinen Kokoomus r.p., ruotsiksi Samlingsp...",0213498-5,NaN,NaN,NaN,2.8,NaN,NaN,3358.00,Antti,Kaarlela,Lapin vaalipiiri,KOK,2023

In [31]:
kuntavaalit_yhteensä_all.to_csv("files/outputs/eduskuntavaalit_financial_line_items.csv", index=False)

kuntavaalit_yhteensä_2023 = kuntavaalit_yhteensä_all[kuntavaalit_yhteensä_all["Vuosi"]==2023]
kuntavaalit_yhteensä_all.groupby(["Tukija", "Tuen saajan puolue"])[["Tuen maara"]].mean()

                                                    Tuen maara
Tukija                          Tuen saajan puolue
AALTO Development Oy            KOK                     2940.0
AC Cranes Trading Oy'           KOK                     2000.0
AKAVA RY                        KOK                     1645.0
AKT:n sos.dem ryhmä             SDP                     1650.0
AM-Company Finland Oy           PS                      6000.0
...                                                        ...
ÅLÄNDSK CENTER R.F.             ÅS\t                    6000.0
ÅLÄNDSK SAMLING R.F.            ÅS                      1389.0
ÅLÄNDSK UNGCENTER R.F.          ÅS                      2000.0
Ålands socialdemokrater         ÅS                       800.0
Åminneforsin Työväenyhdistys ry SDP                      500.0

[1218 rows x 1 columns]

In [29]:
kuntavaalit_yhteensä_2023.groupby(["Tukija", "Tuen saajan puolue"])[["Tuen maara"]].mean()

                                                                       Tuen maara
Tukija                                             Tuen saajan puolue
AALTO Development Oy                               KOK                     2940.0
AC Cranes Trading Oy'                              KOK                     2000.0
AMS Base Assets Oy                                 PS                      5000.0
APV Isännöintipalvelu Ky                           PS                      1500.0
AV Capital Oy                                      PS                      5990.0
...                                                                           ...
Yhteiskunnallinen Keskusteluseura Pirkanmaan Pa... SDP                      500.0
Ylä-Kainuun Perussuomalaiset ry                    PS                       500.0
Ylöjärven Perussuomalaiset ry                      PS                      1860.0
Zewertools Sales EU Oy                             KOK                     2000.0
Äänekosken Vihreät ry                              VIHR                    1000.0

[323 rows x 1 columns]