# Parliamentary Candidate Data

In [19]:
import pandas as pd
pd.set_option('display.max_columns', None)

eduskuntavaalit_ehdokas_sarakkeet = list(pd.read_csv("files/Results_title_rows_EN_ehdokas.csv"))

years_data = {
    2011: {
        'results': "files/election_results_by_candidate/e-2011_teat_maa.csv"
    },
    2015: {
        'results': "files/election_results_by_candidate/e-2015_teat_maa.csv"
    },
    2019: {
        'results': "files/election_results_by_candidate/ekv-2019_teat_maa.csv"
    },
    2023: {
        'results': "files/election_results_by_candidate/ekv-2023_teat_maa.csv"
    }
}

def process_voting_data(years_data):
    """Function for preparing voting data to be municipal results only."""

    all_years_data = []
    for year, paths in years_data.items():
        print(f"Processing {year}...")

        kuntavaalit_ehdokas = pd.read_csv(paths['results'], sep=";", on_bad_lines='warn', encoding='latin-1', names=eduskuntavaalit_ehdokas_sarakkeet, index_col=False)

        kuntavaalit_ehdokas['Year'] = str(year) # Year column for classification later

        kuntavaalit_ehdokas["LR_cand-id"] = (
            kuntavaalit_ehdokas["Candidate number"].astype(str).str.strip() + "-" +
            kuntavaalit_ehdokas["Name of a municipality/electoral district/voting area in Finnish"].str.strip() + "-" + kuntavaalit_ehdokas["Area type"] + "-" + kuntavaalit_ehdokas['Year']
        )
        all_years_data.append(kuntavaalit_ehdokas)

    results = pd.concat(all_years_data, ignore_index=True)
    results = results.drop(results[results['Area type']!="V"].index) # K stands for the total municipal election
    return results

kuntavaalit_results = process_voting_data(years_data)
display(kuntavaalit_results)

# # Combine all years into one dataframe
#
# print(f"In total, there were {len(all_years_data[0])} candidates recorded from 2012; {len(all_years_data[1])} from 2017; {len(all_years_data[2])} from 2021; and {len(all_years_data[3])} from 2025.")

Processing 2011...

C:\Users\kaife\AppData\Local\Temp\ipykernel_22108\1132518150.py:28: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  kuntavaalit_ehdokas = pd.read_csv(paths['results'], sep=";", on_bad_lines='warn', encoding='latin-1', names=eduskuntavaalit_ehdokas_sarakkeet, index_col=False)

Processing 2015...

C:\Users\kaife\AppData\Local\Temp\ipykernel_22108\1132518150.py:28: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  kuntavaalit_ehdokas = pd.read_csv(paths['results'], sep=";", on_bad_lines='warn', encoding='latin-1', names=eduskuntavaalit_ehdokas_sarakkeet, index_col=False)

Processing 2019...

C:\Users\kaife\AppData\Local\Temp\ipykernel_22108\1132518150.py:28: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  kuntavaalit_ehdokas = pd.read_csv(paths['results'], sep=";", on_bad_lines='warn', encoding='latin-1', names=eduskuntavaalit_ehdokas_sarakkeet, index_col=False)

Processing 2023...

C:\Users\kaife\AppData\Local\Temp\ipykernel_22108\1132518150.py:28: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  kuntavaalit_ehdokas = pd.read_csv(paths['results'], sep=";", on_bad_lines='warn', encoding='latin-1', names=eduskuntavaalit_ehdokas_sarakkeet, index_col=False)

,Election type,Electoral district / county number,Municipality number,Area type,Voting area identifier,Abbreviation for an electoral district / a county in Finnish,Abbreviation for an electoral district / a county in Swedish,Permanent party identifier,Standard party number,List order number,Electoral alliance number,Abbreviated name of a political party/group in Finnish,Abbreviated name of a political party/group in Swedish,Abbreviated name of a political party/group in English,Candidate number,Name of a municipality/electoral district/voting area in Finnish,Name of a municipality/electoral district/voting area in Swedish,A person’s first name,A person’s last name,Gender,Age on election day,Profession,Code for place of residence,The name of a place of residence in Finnish,The name of a place of residence in Swedish,Candidate’s language,Member of the European Parliament,Member of Parliament,Municipal councillor,County councillor,Abbreviated name of the first comparison election,Number of votes in the first comparison election,Number of votes cast in advance,Number of votes cast on election day,Total number of votes,Percentage (%) of votes cast in advance,Percentage (%) of votes on election day,Percentage (%) of the total number of votes,Elected information,Comparative index,Position,Final position,Calculation status,Calculation phase,Latest update,Year,LR_cand-id
42720,E,1,***,V,****,HEL,HEL,13,5,1,1,VIHR,GRÖNA,GREEN,2,Helsingin vaalipiiri,Helsingfors valkrets,Zahra ...,Abdulla ...,2,45,kätilö ...,91,Helsinki,Helsingfors,,,,,,,0000000,1517,2045,3562,11,10,10,3,7254000,45,45,V,T,20131212175905,2011,2-Helsingin vaalipiiri-V-2011
42721,E,1,***,V,****,HEL,HEL,13,5,1,1,VIHR,GRÖNA,GREEN,3,Helsingin vaalipiiri,Helsingfors valkrets,Outi ...,Alanko-Kahiluoto ...,2,44,"kansanedustaja, tutkija ...",91,Helsinki,Helsingfors,,,1,,,,0000000,1726,3514,5240,12,17,15,1,14508000,21,21,V,T,20131212175905,2011,3-Helsingin vaalipiiri-V-2011
42722,E,1,***,V,****,HEL,HEL,13,5,1,1,VIHR,GRÖNA,GREEN,4,Helsingin vaalipiiri,Helsingfors valkrets,Verna ...,Castrén ...,2,21,opiskelija ...,91,Helsinki,Helsingfors,,,,,,,0000000,266,429,695,2,2,2,3,3054316,97,97,V,T,20131212175905,2011,4-Helsingin vaalipiiri-V-2011
42723,E,1,***,V,****,HEL,HEL,13,5,1,1,VIHR,GRÖNA,GREEN,5,Helsingin vaalipiiri,Helsingfors valkrets,Pekka ...,Haavisto ...,1,53,"kansanedustaja, ulkoministerin erityisedustaja...",91,Helsinki,Helsingfors,,,1,,,,0000000,3026,4444,7470,21,22,21,1,19344000,14,14,V,T,20131212175905,2011,5-Helsingin vaalipiiri-V-2011
42724,E,1,***,V,****,HEL,HEL,13,5,1,1,VIHR,GRÖNA,GREEN,6,Helsingin vaalipiiri,Helsingfors valkrets,Kimmo ...,Helistö ...,1,49,tuottaja ...,91,Helsinki,Helsingfors,,,,,,,0000000,229,469,698,2,2,2,3,3224000,94,94,V,T,20131212175905,2011,6-Helsingin vaalipiiri-V-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987154,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,109,Lapin vaalipiiri,Lapplands valkrets,Juhani ...,Mykkänen ...,1,63,eläkeläinen ...,698,Rovaniemi,Rovaniemi,FI,,,,,EKV-2019,0000000,9,1,10,0,0,0,3,153875,102,102,V,T,20230405170638,2023,109-Lapin vaalipiiri-V-2023
1987155,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,110,Lapin vaalipiiri,Lapplands valkrets,Jatta ...,Mäkikyrö ...,2,37,sairaanhoitaja YAMK ...,976,Ylitornio,Övertorneå,FI,,,,,EKV-2019,0000000,66,39,105,1,1,1,3,205167,97,97,V,T,20230405170638,2023,110-Lapin vaalipiiri-V-2023
1987156,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,111,Lapin vaalipiiri,Lapplands valkrets,Jonna ...,Pakisjärvi ...,2,46,sairaanhoitaja ...,241,Keminmaa,Keminmaa,FI,,,1,,EKV-2019,0000000,148,92,240,2,3,2,3,410333,83,83,V,T,20230405170638,2023,111-Lapin vaalipiiri-V-2023
1987157,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,112,Lapin vaalipiiri,Lapplands valkrets,Krista ...,Stauffer ...,2,45,"logistiikka-asiantuntija, kansainvälisten toim...",758,Sodankylä,Sodankylä,FI,,,1,1,EKV-2019,0000000,96,80,176,1,2,2,3,307750,89,89,V,T,20230405170638,2023,112-Lapin vaalipiiri-V-2023
1987158,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,113,Lapin vaalipiiri,Lapplands valkrets,Inkeri ...,Yritys ...,2,68,"oikeusnotaari, kunnallisneuvos ...",261,Kittilä,Kittilä,FI,,,1,1,EKV-2019,0000000,174,91,265,3,3,3,3,615500,79,79,V,T,20230405170638,2023,113-Lapin vaalipiiri-V-2023

In [21]:
print(kuntavaalit_results["Total number of votes"].describe())
print(len(pd.unique(kuntavaalit_results["LR_cand-id"])))
# kuntavaalit_results["A person’s last name"] = kuntavaalit_results["A person’s last name"].strip()
display(kuntavaalit_results.loc[kuntavaalit_results["A person’s last name"].astype(str).str.strip() == "Mäkikyrö"])

count     9353.000000
mean      1292.157917
std       2368.212544
min          1.000000
25%        110.000000
50%        432.000000
75%       1390.000000
max      43437.000000
Name: Total number of votes, dtype: float64
9353

,Election type,Electoral district / county number,Municipality number,Area type,Voting area identifier,Abbreviation for an electoral district / a county in Finnish,Abbreviation for an electoral district / a county in Swedish,Permanent party identifier,Standard party number,List order number,Electoral alliance number,Abbreviated name of a political party/group in Finnish,Abbreviated name of a political party/group in Swedish,Abbreviated name of a political party/group in English,Candidate number,Name of a municipality/electoral district/voting area in Finnish,Name of a municipality/electoral district/voting area in Swedish,A person’s first name,A person’s last name,Gender,Age on election day,Profession,Code for place of residence,The name of a place of residence in Finnish,The name of a place of residence in Swedish,Candidate’s language,Member of the European Parliament,Member of Parliament,Municipal councillor,County councillor,Abbreviated name of the first comparison election,Number of votes in the first comparison election,Number of votes cast in advance,Number of votes cast on election day,Total number of votes,Percentage (%) of votes cast in advance,Percentage (%) of votes on election day,Percentage (%) of the total number of votes,Elected information,Comparative index,Position,Final position,Calculation status,Calculation phase,Latest update,Year,LR_cand-id
1987155,E,13,***,V,****,LAP,LAP,1315,99,15,14,YL1,YL1,YL1,110,Lapin vaalipiiri,Lapplands valkrets,Jatta ...,Mäkikyrö ...,2,37,sairaanhoitaja YAMK ...,976,Ylitornio,Övertorneå,FI,,,,,EKV-2019,0000000,66,39,105,1,1,1,3,205167,97,97,V,T,20230405170638,2023,110-Lapin vaalipiiri-V-2023

In [23]:
kuntavaalit_municipal_candidates = kuntavaalit_results.groupby(['Name of a municipality/electoral district/voting area in Finnish', 'Year']).agg(num_candidates=('Year', 'size'), total_votes=('Total number of votes', 'sum')).reset_index()
kuntavaalit_municipal_candidates["Name of a municipality/electoral district/voting area in Finnish"] = kuntavaalit_municipal_candidates["Name of a municipality/electoral district/voting area in Finnish"].str.strip()

kuntavaalit_results.to_csv("files/outputs/parliamentary_election_results_by_candidate.csv")
kuntavaalit_municipal_candidates.to_csv("files/outputs/parliamentary_macro_per_year.csv")

display(kuntavaalit_municipal_candidates)

,Name of a municipality/electoral district/voting area in Finnish,Year,num_candidates,total_votes
0,Ahvenanmaan maakunnan vaalipiiri,2011,8,10503
1,Ahvenanmaan maakunnan vaalipiiri,2015,7,12187
2,Ahvenanmaan maakunnan vaalipiiri,2019,5,13076
3,Ahvenanmaan maakunnan vaalipiiri,2023,15,13383
4,Etelä-Savon vaalipiiri,2011,94,83432
5,Helsingin vaalipiiri,2011,267,347885
6,Helsingin vaalipiiri,2015,269,359875
7,Helsingin vaalipiiri,2019,286,385560
8,Helsingin vaalipiiri,2023,293,388501
9,Hämeen vaalipiiri,2011,132,202689
10,Hämeen vaalipiiri,2015,127,202446
11,Hämeen vaalipiiri,2019,155,205738
12,Hämeen vaalipiiri,2023,144,207266
13,Kaakkois-Suomen vaalipiiri,2015,149,245545
14,Kaakkois-Suomen vaalipiiri,2019,179,244974
15,Kaakkois-Suomen vaalipiiri,2023,158,228628
16,Keski-Suomen vaalipiiri,2011,141,148433
17,Keski-Suomen vaalipiiri,2015,127,151269
18,Keski-Suomen vaalipiiri,2019,153,154375
19,Keski-Suomen vaalipiiri,2023,146,153254
20,Kymen vaalipiiri,2011,118,169102
21,Lapin vaalipiiri,2011,114,99357
22,Lapin vaalipiiri,2015,118,100871
23,Lapin vaalipiiri,2019,122,99807
24,Lapin vaalipiiri,2023,112,97904
25,Oulun vaalipiiri,2011,156,243662
26,Oulun vaalipiiri,2015,165,249652
27,Oulun vaalipiiri,2019,184,258858
28,Oulun vaalipiiri,2023,177,261715
29,Pirkanmaan vaalipiiri,2011,207,273920
30,Pirkanmaan vaalipiiri,2015,203,278073
31,Pirkanmaan vaalipiiri,2019,251,299154
32,Pirkanmaan vaalipiiri,2023,239,309941
33,Pohjois-Karjalan vaalipiiri,2011,108,87185
34,Pohjois-Savon vaalipiiri,2011,118,131369
35,Satakunnan vaalipiiri,2011,97,126108
36,Satakunnan vaalipiiri,2015,126,122334
37,Satakunnan vaalipiiri,2019,117,124871
38,Satakunnan vaalipiiri,2023,124,119611
39,Savo-Karjalan vaalipiiri,2015,139,216880
40,Savo-Karjalan vaalipiiri,2019,165,221529
41,Savo-Karjalan vaalipiiri,2023,156,224357
42,Uudenmaan vaalipiiri,2011,406,507189
43,Uudenmaan vaalipiiri,2015,394,520119
44,Uudenmaan vaalipiiri,2019,492,546672
45,Uudenmaan vaalipiiri,2023,485,565306
46,Vaasan vaalipiiri,2011,158,248881
47,Vaasan vaalipiiri,2015,156,245817
48,Vaasan vaalipiiri,2019,168,250901
49,Vaasan vaalipiiri,2023,161,246966
50,Varsinais-Suomen vaalipiiri,2011,191,259856
51,Varsinais-Suomen vaalipiiri,2015,166,263394
52,Varsinais-Suomen vaalipiiri,2019,191,276401
53,Varsinais-Suomen vaalipiiri,2023,214,278772